### ISSUE TITLE
Matrix exists both in VelcroPhysics.MonoGame and MonoGame.Framework

### ISSUE THREAD

**Issue by KirilAngelov** [egordorichev/Lens#228]
Hello Egor,

First I want to apologise if this is a mistake on my behalf.

Having issues running the project.
Currently, I am building and running the Desktop project in the Lens.sln, but when I do that I get the error : 

The type 'Matrix'(same with Vector2) exists in both 'VelcroPhysics.MonoGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'MonoGame.Framework, Version=3.8.0.13, Culture=neutral, PublicKeyToken=null'	
I tried working around with the namespaces, but I could not make it work.

Also there are some missing dlls when i try to build : 
In the project BurningKnight and Desktop, there is a Lens.dll missing
Again in Desktop there is a BurningKnight.dll missing.

Best regards,
Kiril.

**Comment by egordorichev** [comment]
It looks like an issue with monogame update or smth. I'm very sorry, very busy with a lot (like very a lot) of projects right now, can't help you debug/fix this. Lens dll should be a result of the project Lens compilation, so I guess its missing because it couldn't compile because of the Matrix clash. The only thing I can propose to you is to rename Matrix class in VelcroPhysics into something like MatrixTest (via refractor, so every type Matrix becomes MatrixTest only in VelcroPhysics).

I hope this helps,
Egor

**Comment by xelfe** [comment]
> 
> 
> Hello Egor,
> 
> First I want to apologise if this is a mistake on my behalf.
> 
> Having issues running the project.
> Currently, I am building and running the Desktop project in the Lens.sln, but when I do that I get the error :
> 
> The type 'Matrix'(same with Vector2) exists in both 'VelcroPhysics.MonoGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'MonoGame.Framework, Version=3.8.0.13, Culture=neutral, PublicKeyToken=null'
> I tried working around with the namespaces, but I could not make it work.
> 
> Also there are some missing dlls when i try to build :
> In the project BurningKnight and Desktop, there is a Lens.dll missing
> Again in Desktop there is a BurningKnight.dll missing.
> 
> Best regards,
> Kiril.

Let me know if you found something. I'm stuck like you describe...

**Comment by OAguinagalde** [comment]
This has been a common issue whenever I try to use monogame related libraries that have duplicate stuff inside. I'm sure there is a better and simpler way of making this work, but I usually just comment out the classes that are duplicated. In the case of Burning Knight the only classes that are duplicated or that cause problems (last time I tried the repo) where Matrix Vector2 and Vector3. So if you just comment out the classes/structs definition (literally comment out or just delete) it should work.

**Comment by egordorichev** [comment]
Heads up, guys: 

```csharp
#if !XNA && !WINDOWS_PHONE && !XBOX && !ANDROID && !MONOGAME
```

The Matrix class should be ignored by the compiler when compiling for MonoGame, but for some reason, it didn't work for everyone, so I manually made sure that `MONOGAME` is defined a line above.

That should fully fix it.
